In [1]:
# Importing dependiences 
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [2]:
# Importing data from csv files by year
data_2022 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2022.csv")
data_2021 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2021.csv")
data_2020 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2022.csv")
data_2019 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2022.csv")
data_2018 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2018.csv")
data_2017 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2017.csv")
data_2016 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2016.csv")
data_2015 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2015.csv")
data_2014 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2014.csv")
data_2013 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2013.csv")
data_2012 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2012.csv")
data_2011 = pd.read_csv("../Data/Raw_Data/pitch_tempo_2011.csv")

In [3]:
# Inserting new column 'year' in each table
data_2022.insert(0, 'year', 2022)
data_2021.insert(0, 'year', 2021)
data_2020.insert(0, 'year', 2020)
data_2019.insert(0, 'year', 2019)
data_2018.insert(0, 'year', 2018)
data_2017.insert(0, 'year', 2017)
data_2016.insert(0, 'year', 2016)
data_2015.insert(0, 'year', 2015)
data_2014.insert(0, 'year', 2014)
data_2013.insert(0, 'year', 2013)
data_2012.insert(0, 'year', 2012)
data_2011.insert(0, 'year', 2011)

In [5]:
pitch_tempo_df = pd.concat([data_2022,
                          data_2021,
                          data_2020,
                          data_2019,
                          data_2018,
                          data_2017,
                          data_2016,
                          data_2015,
                          data_2014,
                          data_2013,
                          data_2012,
                          data_2011])
pitch_tempo_df

,year,entity_id,entity_name,entity_code,team_id,total_pitches,total_pitches.1,total_pitches_empty,median_seconds_empty,total_pitches_onbase,median_seconds_empty.1,freq_hot,freq_warm,freq_cold
0,2022,425877,"Molina, Yadier",Pit,138,19,19,8.0,6.471,11.0,6.471,0.947368,0.052632,0.0
1,2022,571976,"Myers, Wil",Pit,135,18,18,15.0,7.192,3.0,7.192,1.000000,0.000000,0.0
2,2022,608703,"Reynolds, Matt",Pit,113,6,6,2.0,7.766,4.0,7.766,1.000000,0.000000,0.0
3,2022,405395,"Pujols, Albert",Pit,138,13,13,5.0,7.977,8.0,7.977,1.000000,0.000000,0.0
4,2022,571466,"Barnhart, Tucker",Pit,116,8,8,3.0,8.047,5.0,8.047,1.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,2011,572816,"Dickerson, Corey",Pit,138,9,9,NaN,NaN,9.0,NaN,1.000000,0.000000,0.0
866,2011,503556,"Gonzalez, Marwin",Pit,147,3,3,NaN,NaN,3.0,NaN,0.333333,0.666667,0.0
867,2011,570560,"Sanchez, Carlos",Pit,111,5,5,NaN,NaN,5.0,NaN,1.000000,0.000000,0.0
868,2011,670102,"Francis, Bowden",Pit,141,2,2,NaN,NaN,2.0,NaN,0.000000,1.000000,0.0
869,2011,594838,"Gosselin, Phil",Pit,108,2,2,NaN,NaN,2.0,NaN,1.000000,0.000000,0.0